spring:
    application:
      name: restFulApi
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
    jda:
      show-sql: true
    hibernate:
      ddl-auto: create
    data:
      rest:
        base-path: v2
        default-page-size: 10
server:
  servlet:
    context-path: /api